import type { Metadata } from "next";
import localFont from "next/font/local";
import MainHeader from "../../components/main-header/main-header";
import { Providers } from "@/components/main-header/providers";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../../styles/layout.module.css";
// import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styles.container}`}
      >
        <Providers locale={params.locale}>
          <header className={styles.header}>
            <MainHeader />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
